### ISSUE TITLE
Could you download all notebooks with project files.

### ISSUE THREAD

**Issue by HarishOsthe** [Ebadm/Coursera-Machine-Learning-Specialization#1]
Hi, @Ebadm Great repo really useful,

If you still have the subscription for the course,
Could you download the notebooks with the custom libraries that Coursera used? Ex: C2_W2_Backprop.ipynb

![image](https://user-images.githubusercontent.com/44117452/231060718-d01627bd-cadf-485b-9d6b-e98d49f832ee.png)

This link might be [helpful](https://www.coursera.support/s/article/360004990332-Download-Jupyter-Workspace-files?language=en_US)

Thank You

**Comment by Ebadm** [comment]
Thank you for raising this issue, I have fixed it. You can find lab_utils_backprop.py now

**Comment by HarishOsthe** [comment]
Hey @Ebadm Thanks for updating, 

There are other assignments which requires different custom libraries, so could download the entire assignment as stated in this video https://www.youtube.com/watch?v=oDTugD5ohgU

You will get a zip file with all the files in it.

If you are busy you can share me the coursera login credentials on LinkedIn. ill update the project and make a MR.

Thank You
